# Ejercicios de probabilidad

## Ejercicio 1 

Dos dados se lanzan una vez y se observa el total obtenido. Usa una simulación para encontrar la probabilidad estimada de que la puntuación sea mayor a 7 o un número par. Una simulación es una repetición del mismo experimento multiples veces para observar su comportamiento:

- Ejecuta el experimento 1000 veces (lanza 2 dados 1000 veces, y suma el número de ambos dados).
- Lleva una cuenta de los números y las veces que la suma fue mayor a 7 o un número par.
- Divide el número del paso 2 entre el número de iteraciones(1000).

In [1]:
import numpy as np

### Declarar las variables y simular

In [2]:
lanzamientos = 100
dado1 = np.random.randint(1, 7, lanzamientos)  
dado2 = np.random.randint(1, 7, lanzamientos)
suma = dado1 + dado2
condicion1 = (suma > 7) | (suma %2 == 0)
cumplen = np.sum(condicion1)
probabilidad_cumplen = cumplen / lanzamientos
probabilidad_cumplen

np.float64(0.7)

### Podemos concluir que la probabilidad siempre va a estar entre el 60 y 70 % no incluidos.

## Ejercicio 2

Una caja contiene 10 bolas blancas, 20 bolas rojas y 30 bolas verdes. Si tomamos 5 bolas de la caja reemplazándolas (tomando una bola, anotando el color y luego regresandola a la caja). Queremos saber la probabilidad de:

1. Tomar 3 blancas y 2 rojas.
2. Tomar todas del mismo color.

Ejecuta el experimento 1000 veces y calcula las probabilidades que mencionan.

In [3]:
ball_box = {}

# Crea la cajas con las bolas
for i in range(60):
    if i < 10:
        ball_box[i] = "White"
    elif (i > 9) and (i < 30):
        ball_box[i] = "Red"
    else:
        ball_box[i] = "Green"

print(ball_box)
ball_box = np.array(['White'] * 10 + ['Red'] * 20 + ['Green'] * 30)

{0: 'White', 1: 'White', 2: 'White', 3: 'White', 4: 'White', 5: 'White', 6: 'White', 7: 'White', 8: 'White', 9: 'White', 10: 'Red', 11: 'Red', 12: 'Red', 13: 'Red', 14: 'Red', 15: 'Red', 16: 'Red', 17: 'Red', 18: 'Red', 19: 'Red', 20: 'Red', 21: 'Red', 22: 'Red', 23: 'Red', 24: 'Red', 25: 'Red', 26: 'Red', 27: 'Red', 28: 'Red', 29: 'Red', 30: 'Green', 31: 'Green', 32: 'Green', 33: 'Green', 34: 'Green', 35: 'Green', 36: 'Green', 37: 'Green', 38: 'Green', 39: 'Green', 40: 'Green', 41: 'Green', 42: 'Green', 43: 'Green', 44: 'Green', 45: 'Green', 46: 'Green', 47: 'Green', 48: 'Green', 49: 'Green', 50: 'Green', 51: 'Green', 52: 'Green', 53: 'Green', 54: 'Green', 55: 'Green', 56: 'Green', 57: 'Green', 58: 'Green', 59: 'Green'}


In [4]:
tomar_3w2r = 0
tomar_3samecolor = 0

# Contar resultados por cada fila

In [14]:
# lanzamientos=1000 ya declarada
muestreo = np.random.choice(ball_box, size=(lanzamientos,5), replace=True) 
conteo_W = np.sum(muestreo == 'White', axis = 1)
conteo_R = np.sum(muestreo == 'Red', axis = 1)
conteo_G = np.sum(muestreo == 'Green', axis = 1)
muestreo


array([['Green', 'Green', 'White', 'Green', 'Green'],
       ['Green', 'White', 'Green', 'Green', 'Red'],
       ['White', 'Red', 'Green', 'Red', 'Red'],
       ['Red', 'Green', 'Green', 'White', 'Red'],
       ['White', 'Green', 'Red', 'Green', 'Green'],
       ['Red', 'Red', 'Green', 'Green', 'White'],
       ['Green', 'Red', 'Green', 'White', 'Red'],
       ['White', 'White', 'Green', 'Green', 'Red'],
       ['White', 'Green', 'Red', 'Green', 'Red'],
       ['Green', 'Green', 'Green', 'White', 'Red'],
       ['Green', 'White', 'Green', 'Red', 'Red'],
       ['White', 'Red', 'Green', 'Red', 'Green'],
       ['White', 'Red', 'White', 'Green', 'White'],
       ['Red', 'White', 'Green', 'White', 'Green'],
       ['Red', 'Green', 'White', 'Red', 'Red'],
       ['Green', 'Green', 'Green', 'Red', 'Green'],
       ['Green', 'White', 'Green', 'Red', 'Green'],
       ['White', 'Red', 'Red', 'White', 'White'],
       ['Green', 'Green', 'Red', 'Green', 'Green'],
       ['White', 'Green', 'Red',

# Declaración de condiciones

In [15]:
condition1 = (conteo_W == 3) & (conteo_R == 2)
condition2 = (conteo_W == 5) | (conteo_R == 5) | (conteo_G == 5)

# Comprobacion de conteos

In [16]:
conteo_W

array([1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 3, 2, 1, 0, 1, 3, 0, 1, 1, 1,
       0, 1, 0, 2, 1, 0, 1, 1, 0, 1, 0, 2, 2, 3, 1, 0, 2, 0, 0, 1, 0, 1,
       1, 1, 0, 2, 2, 2, 0, 1, 1, 1, 0, 1, 2, 0, 1, 0, 2, 0, 0, 0, 2, 1,
       2, 1, 1, 0, 1, 0, 0, 3, 1, 3, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 0, 2,
       0, 1, 2, 2, 1, 0, 0, 1, 0, 2, 1, 0])

In [17]:
conteo_R

array([0, 1, 3, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 3, 1, 1, 2, 1, 2, 2, 1,
       1, 1, 3, 2, 2, 1, 2, 1, 3, 1, 3, 2, 0, 0, 2, 0, 1, 2, 3, 2, 1, 1,
       2, 4, 3, 0, 2, 2, 3, 1, 2, 4, 1, 2, 0, 2, 2, 0, 2, 1, 3, 2, 1, 1,
       0, 1, 1, 4, 1, 2, 4, 0, 3, 1, 2, 0, 3, 2, 1, 0, 1, 0, 3, 3, 3, 1,
       3, 4, 0, 0, 3, 0, 0, 3, 2, 2, 2, 1])

In [18]:
conteo_G

array([4, 3, 1, 2, 3, 2, 2, 2, 2, 3, 2, 2, 1, 2, 1, 4, 3, 0, 4, 2, 2, 3,
       4, 3, 2, 1, 2, 4, 2, 3, 2, 3, 2, 1, 3, 2, 2, 5, 2, 3, 2, 2, 4, 3,
       2, 0, 2, 3, 1, 1, 2, 3, 2, 0, 4, 2, 3, 3, 2, 5, 1, 4, 2, 3, 2, 3,
       3, 3, 3, 1, 3, 3, 1, 2, 1, 1, 2, 4, 2, 1, 3, 5, 3, 3, 2, 2, 2, 2,
       2, 0, 3, 3, 1, 5, 5, 1, 3, 1, 2, 4])

# Calculo de probabilidades

In [19]:
probabilidad_cond1 = np.sum(condition1) / lanzamientos
probabilidad_cond1

np.float64(0.01)

In [20]:
probabilidad_cond2 = np.sum(condition2) / lanzamientos
probabilidad_cond2

np.float64(0.05)